CREATE DATABASE student_achievement;
CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  college_id VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  role VARCHAR(20) NOT NULL
);